### PR TITLE
Added vertx-maven-plugin and its related configurations

### PR DESCRIPTION
**Pull request by kameshsampath**
Please merge and test

### CODE REVIEW

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
Thanks just ran it locally and it works, however not sure why SVC shows the port as 0 and not the actual external port

    [INFO] F8:[SVC] vertx-web: http://192.168.64.20:0

I had to use gofabric8 service vertx-web to get the external url so I can hit it from my web browser. The other quickstarts report correct port number than 0.

**Comment by davsclaus** [comment]
[merge]

**Comment by kameshsampath** [comment]
@davsclaus - I did fabric8:run, since am using ingress i see the url available and application working. will check the service type change tomorrow and see. Also we need to make this use VertxGenerator instead of java exec. @rhuss  your comments ?

**Pull request merged**
